### ISSUE TITLE
This is a personal difficulty, I would be very glad if you could help me out.

### ISSUE THREAD

**Issue by yuzu-ogura** [Wind-River/vxworks7-ros2-build#107]
The problem I'm solving:
I plan to build the `library: fastrtps` for `VxWorks.` Long time ago, I try many times to build the `libfastrtps` accroding the `fast-dds official website`, but due to couldn't compile `asio`, so I give up finally. Recently, I'm going to build this repository to get the libfastrtps indirectly. However my network is very instability, so I build failed ascribe to `git clone` fails, like below: 
![image](https://github.com/Wind-River/vxworks7-ros2-build/assets/166282486/d0f89970-235c-4359-889d-71833cf26771)
So what should I do can I finish the building of  `library: fastrtps` for `VxWorks.` 
I'm looking forward to your reply, thanks a lot.

**Comment by razr** [comment]
if you want to build `FastDDS` you can modify `packages.mk` file

```diff
$ git diff pkg/ros2/files/humble/packages.mk
diff --git a/pkg/ros2/files/humble/packages.mk b/pkg/ros2/files/humble/packages.mk
index d511a23..a3d31bf 100644
--- a/pkg/ros2/files/humble/packages.mk
+++ b/pkg/ros2/files/humble/packages.mk
@@ -71,9 +71,7 @@ ROS2_PYTHON_TOOLS=ros2action ros2cli ros2component ros2doctor \
        ros2interface ros2lifecycle ros2multicast ros2node ros2param ros2pkg \
        ros2run ros2service ros2topic

-PKG_PKGS_UP_TO+=$(ROS2_EXAMPLES) \
-       $(ROS2_PYTHON_TOOLS) \
-       sros2
+PKG_PKGS_UP_TO+=fastrtps

 #      pendulum_control

```

and then run

```bash
 DEFAULT_BUILD="sdk unixextra asio tinyxml2 ros2" make
```

The first change says build system to build `fastrtps` only. The second command says build system to build packages that are necessary for the `fastrtps`
