### ISSUE TITLE
Reference of git dashing-devel branch in turtlebot3 + util repos

### ISSUE THREAD

**Issue by Prof-Florian-Kuenzner** [Wind-River/vxworks7-ros2-build#13]
Hello,

Yesterday, the build of the ros2-build `dashing-release-SR0640-python` run into some build errors, which was caused by too new versions of turtlebot3 + utils (DynamixelSDK +hls_lfcd_lds_driver), where the patch files didn't work correctly.

After changing the `pkg/turtlebot3/Makefile` line 36 to `PKG_REPO_COMMIT_ID = dashing-devel` everything works fine.

Is there a reason, why `PKG_REPO_COMMIT_ID = ros2-devel` is used here: https://github.com/Wind-River/vxworks7-ros2-build/blob/882173a2cc9377decec42397cb669760304c8cfb/pkg/turtlebot3/Makefile#L36

**Comment by razr** [comment]
@Prof-Florian-Kuenzner thanks for reporting it. In the past, there was only ROS2 branch ```ros2-devel```. I'll fix it this week.

**Comment by Prof-Florian-Kuenzner** [comment]
@razr thank you. This looks good. I think we can close the issue now.
