### ISSUE TITLE
Building vxros2build container image gives NO_PUBKEY error

### ISSUE THREAD

**Issue by bengelman** [Wind-River/vxworks7-ros2-build#2]
When running the command "sudo docker build -t vxros2build:1.0 ." I get the following error:

W: GPG error: http://packages.ros.org/ros2/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: The repository 'http://packages.ros.org/ros2/ubuntu bionic InRelease' is not signed. 

Adding the line "RUN curl http://repo.ros2.org/repos.key | apt-key add -" to vxros2build/Dockerfile solves this.

**Comment by razr** [comment]
[fixed](https://github.com/Wind-River/vxworks7-ros2-build/commit/7e4fb85e1381b6e618b5794680d3ff12a4e904cb)
