### ISSUE TITLE
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)). Executing: /tmp/apt-key-gpghome.7L3MDmqoQB/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 gpg: CRC error; 69B924 - 6C9712 gpg: read_block: read error: Invalid keyring gpg: Total number processed: 0 The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' returned a non-zero code: 2

### ISSUE THREAD

**Issue by enriLoniterp** [Wind-River/vxworks7-ros2-build#50]
i am building vxros2build and it seems it could be errors on private keys, building stop at step 6. In that case it means it doesn't build everything. If i run the last layer built it prints `humble` as $ROS_DISTRO at least

```
Step 6/16 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
 ---> Running in 1c0195ef43d7
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.7L3MDmqoQB/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
gpg: CRC error; 69B924 - 6C9712
gpg: read_block: read error: Invalid keyring
gpg: Total number processed: 0
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' returned a non-zero code: 2

```

**Comment by enriLoniterp** [comment]
Hi @razr ,
it's me again, i've found in `https://answers.ros.org/question/398460/how-to-add-a-pubkey/` that this solution might be old? i've changed with` RUN  apt update &&  apt install curl gnupg lsb-release && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg as suggested in the official guide`

**Comment by enriLoniterp** [comment]
hi again @razr,

Solved many "problems" (i've followed all your instructions) and got this result on distlib module:
```

cd /work/build/colcon/colcon_ws; \
./src/colcon-core/bin/colcon build --merge-install --install-base=/wrsdk/vxsdk/host/x86_64-linux --paths src/*
Traceback (most recent call last):
  File "/work/build/colcon/colcon_ws/./src/colcon-core/bin/colcon", line 57, in <module>
    from colcon_core.package_augmentation.python \
  File "/work/build/colcon/colcon_ws/src/colcon-core/colcon_core/package_augmentation/python.py", line 11, in <module>
    from distlib.util import parse_requirement
ModuleNotFoundError: No module named 'distlib'
make[1]: *** [Makefile:65: colcon.build] Error 1
make[1]: Leaving directory '/work/pkg/colcon'
make: *** [Makefile:22: all] Error 1
wruser@b64a95a9e5d9:/work$ 

```

**Comment by razr** [comment]
I'm not sure what you mean by "Solved many problems"
Did you successfully build `vxros2build:humble` docker image?
There are two Guthub actions, that you can use as a reference
- [docker-build](https://github.com/Wind-River/vxworks7-ros2-build/blob/master/.github/workflows/docker-build.yaml)
  - builds both docker images and downloads `vxros2build:humble` as an artifact
- [vxworks-ros2-build](https://github.com/Wind-River/vxworks7-ros2-build/blob/master/.github/workflows/vxworks-ros2-build.yml)
  - makes a complete build cycle (docker images, ROS2 VxWorks build
  - creates and downloads a ros2.img

**Comment by enriLoniterp** [comment]
Yes i've built the images and inside `/work` i did:

1. ` make distclean`
2.  `make`
3.
Following errors reported in the initial comment. (echo $ROS_DISTRO printed humble as specificied in docker file).
I'll follow your suggests and use first method, but then to install the image in VWorks7 what should i do?

Thank for your support @razr, 
Enrico
